app/routes.py
from flask import current_app as app, Blueprint, render_template, flash, redirect, url_for, request, g
import secrets
import os
from app import bcrypt, db
from app.models import User, Products, Notification, add_to_cart, add_to_wishlist
from app.forms import RegisterForm, LoginForm, EditProfileForm, ProductForm, DeleteForm
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='templates', static_folder='static')
product = Blueprint('product', __name__, template_folder='templates', static_folder='static')

@product.before_request
def before_product_request():
    if request.method == 'POST':
        delete_form = DeleteForm()
        if delete_form.validate_on_submit():
            noty = Notification.query.filter_by(user_id=current_user.id).first()
            db.session.delete(noty)
            db.session.commit()

@product.route('/', methods=['POST', 'GET'])
def home():
    products = Products.query.all()
    if current_user.is_authenticated:
        delete = DeleteForm()
        notifs = current_user.notification
        image_file = url_for('static', filename='profile_pic/' + current_user.user_img)
        return render_template('home.html', image_file=image_file, products=products, notifs=notifs)
    else:
        return render_template('home.html', products=products)

@product.route('/add_to_carts/<int:id>')
@login_required
def add_to_carts(id):
    productz = Products.query.get_or_404(id)
    add_to_cart(id)
    notif_message = f"{productz.product_name} has been added to your cart"
    new_notifs = Notification(notification=notif_message, user_id=current_user.id)
    db.session.add(new_notifs)
    db.session.commit()
    return redirect(url_for('product.home'))

@product.route('/add_to_wishlists/<int:id>')
@login_required
def add_to_wishlists(id):
    productz = Products.query.get_or_404(id)
    add_to_wishlist(id)
    notif_mssg = f"{productz.product_name} has been added to your wishlist"
    new_notifs = Notification(notification=notif_mssg, user_id=current_user.id)
    db.session.add(new_notifs)
    db.session.commit()
    return redirect(url_for('product.home'))

@auth.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('product.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        first_name = form.first_name.data.title()
        last_name = form.last_name.data.title()
        username = form.username.data
        email = form.email.data
        user = User(name=f"{first_name} {last_name}", email=email, username=username, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        notif_mssg = f"Welcome, {current_user.name}"
        new_notifs = Notification(notification=notif_mssg, user_id=current_user.id)
        db.session.add(new_notifs)
        db.session.commit()
        flash(f'Account has been created {first_name} {last_name}. Complete your profile.')
        return redirect(url_for('auth.edit_profile', username=user.username))
    return render_template('register.html', form=form)

@auth.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('product.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('product.home'))
        else:
            flash('Login Unsuccessful. Check email or password')
    return render_template('login.html', form=form)

@auth.route('/logout', methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('product.home'))

@auth.route('/profile/<string:username>')
def profile(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('User does not exist')
        return redirect(url_for('product.home'))
    image_profile = url_for('static', filename='profile_pic/' + user.user_img)
    if current_user.is_authenticated:
        image_file = url_for('static', filename='profile_pic/' + current_user.user_img)
        return render_template('profile.html', profile=user, image_profile=image_profile, image_file=image_file)
    else:
        return render_template('profile.html', profile=user, image_profile=image_profile)

def save_pic(form_img):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_img.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/profile_pic', picture_fn)
    form_img.save(picture_path)
    return picture_fn

@auth.route('/edit_profile/<string:username>', methods=['POST', 'GET'])
@login_required
def edit_profile(username):
    if username != current_user.username:
        flash('Cannot edit another user\'s profile')
        return redirect(url_for('auth.edit_profile', username=current_user.username))
    image_file = url_for('static', filename='profile_pic/' + current_user.user_img)
    edit = EditProfileForm()
    edit_profile = User.query.filter_by(username=username).first()
    if edit.validate_on_submit():
        if edit.user_img.data:
            img_file = save_pic(edit.user_img.data)
            current_user.user_img = img_file
        edit_profile.name = f"{edit.first_name.data} {edit.last_name.data}"
        edit_profile.username = edit.username.data
        edit_profile.user_address = edit.user_address.data
        edit_profile.user_description = edit.user_description.data
        edit_profile.user_state = edit.user_state.data
        edit_profile.user_country = edit.user_country.data
        edit_profile.user_gender = edit.user_gender.data
        db.session.commit()
        flash('Profile updated successfully!')
        return redirect(url_for('auth.profile', username=current_user.username))
    elif request.method == 'GET':
        names = edit_profile.name.split()
        edit.first_name.data = names[0]
        edit.last_name.data = names[1]
        edit.username.data = edit_profile.username
        edit.user_address.data = edit_profile.user_address
        edit.user_description.data = edit_profile.user_description
        edit.user_state.data = edit_profile.user_state
        edit.user_country.data = edit_profile.user_country
        edit.user_gender.data = edit_profile.user_gender
    return render_template('edit_profile.html', form=edit, edit_profile=edit_profile, image_file=image_file)

def save_product_pic(form_img):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_img.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/products', picture_fn)
    form_img.save(picture_path)
    return picture_fn

@product.route('/add_product', methods=['POST', 'GET'])
@login_required
def add_product():
    form = ProductForm()
    image_file = url_for('static', filename='profile_pic/' + current_user.user_img)
    if form.validate_on_submit():
        if form.product_img.data:
            pics = [save_product_pic(pictures) for pictures in form.product_img.data]
        product_data = {
            "product_name": form.product_name.data,
            "product_description": form.product_description.data,
            "price": form.price.data,
            "category": form.category.data,
            "user_id": current_user.id
        }
        product = Products(**product_data)
        for i in range(min(len(pics), 5)):
            setattr(product, f"product_img{i+1}", pics[i])
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('product.home'))
    return render_template('add_product.html', form=form, image_file=image_file)

@product.route('/product/<string:product_namez>/<int:product_id>', methods=['POST', 'GET'])
@login_required
def products(product_namez, product_id):
    image_file = url_for('static', filename='profile_pic/' + current_user.user_img)
    products = Products.query.get_or_404(product_id)
    return render_template('products.html', products=products, image_file=image_file)

app/templates/add_product.html
{% extends "base.html" %}

{% block content %}


</style>
<form method='POST' action="" enctype='multipart/form-data'>
        {{ form.hidden_tag() }}
        {{ form.csrf_token }}
            <div class="col-md-7 border-right">
            <div class="p-9 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Add Product</h4>
                </div>

                
                
                <div class="col-md-15">{{ form.product_name.label(class = 'form-control-label') }}
                    {% if form.product_name.errors %}
                      {{ form.product_name (class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.product_name.errors %}
                            <span>{{error}}</span>
                          {% endfor %}
                          {% else %}
                            {{ form.product_name (class = 'form-control') }}
                          {% endif %}


                
                    <div class="col-md-15">{{ form.product_description.label(class = 'form-control-label') }}
                        {% if form.product_description.errors %}
                          {{ form.product_description (class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                              {% for error in form.product_description.errors %}
                                <span>{{error}}</span>
                              {% endfor %}
                              {% else %}
                                {{ form.product_description (class = 'form-control') }}
                              {% endif %}
                    
                              {{ form.price.label (class="form-control-label") }}
                              <div class="input-group mb-3">
                                
                                <span class="input-group-text">$</span>
                                {{ form.price (class="form-control") }}
                                <span class="input-group-text">.00</span>
                              </div>


                    <div class="col-md-15">{{ form.category.label(class = 'form-select-label') }}{{ form.category(class = 'form-select') }}</div>
                    
                    {{ form.product_img.label(class = 'form-control-label') }}
                    {{ form.product_img (class = 'form-control-file') }}
                    {% if form.product_img.errors %}
                          {% for error in form.product_img.errors %}
                            <span class="text-danger">{{error}}</span>
                          {% endfor %}
                          {% endif %}

                </div>
                <div class="mt-5 text-center">{{form.submit (class="btn btn-outline-dark long-button" ) }}</div>
            </div>

    </div>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> {{ title }} </title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type="text/css"  /> 
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css" />
<!-- Bootstrap CSS -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<!-- Bootstrap JS and dependencies -->


</head>

<body>
  <nav class="navbar navbar-icon-top navbar-expand-sm navbar-dark bg-dark  shadow-lg sticky-top">
    <a class="navbar-brand" href="#">TARVEL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        
        {% if current_user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for("product.home") }}">
            <i class="fa fa-home"></i>
            Home
            <span class="sr-only">(current)</span>
            </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fa fa-shopping-cart"></i> Cart ({{ current_user.cart|length }})
        </a>
        </li>
        <li>
          <a class="nav-link" href="#">
            <i class="fa fa-heart"></i> Wishlist ({{ current_user.wishlist|length }})
        </a>
        </li>
        <li>
          <a class="nav-link">
            <i class="fa fa-envelope-o">
              <span class="badge badge-primary">11</span>
            </i>
            Message
          </a>
          
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-bell-o">
              
              <span class="badge badge-primary">{{current_user.notification|length}}</span>
            </i>
            Notification                   

          </a>
          <div class="dropdown-menu pre-scrollable"  style="max-height: 300px; overflow-y: auto;" aria-labelledby="navbarDropdown">
            {% if current_user.notification %} 
            
            <form method="POST">{{ delete.hidden_tag() }}<div class="text-center">{{ delete.delete }}</div></form> 
            {% for mssg in current_user.notification %}
            <p class="dropdown-item">{{ mssg.notification }}</p>
            <div class="dropdown-divider"></div>
            {% endfor %}

            {% else %}
            <p class="dropdown-item">No new notification</p>
          </div>
          {% endif %}
        </li>
        {% endif %}
      </ul>
      
      
      <ul class="navbar-nav ">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false"> <img src="{{ image_file }}" class="rounded-circle" alt="Dropdown Trigger" style="width: 35px; height: 35px;">
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('auth.profile', username=current_user.username)}}">Profile</a></li>
              <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a></li>
              <li><a class="dropdown-item" href="#">Cart</a></li>
              <li><a class="dropdown-item" href="#">Whishlist</a></li>
            </ul>
          </li>


            {% else %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false"> <img src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" class="rounded-circle" alt="Dropdown Trigger" style="width: 35px; height: 35px;">
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{url_for('auth.register')}}">Sign up</a></li>
                <li><a class="dropdown-item" href="{{url_for('auth.login')}}">Login</a></li>
              </ul>
            </li>
            {% endif %}  

        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  
  


  <!-- Products -->
<section>
  <div class="container mt-3">
          
  {% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}

    {% block content %}

    {% endblock %}
</div>

</section>
<!-- Products -->

{% block footer %}
{% endblock %}


  

</body>



<script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> 
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</html>

app/templates/home.html
{% extends 'base.html' %}

{% block content %}


    <!-- Jumbotron -->
    <div class="bg-primary text-white py-5">
      <div class="container py-5">
        <h1>
          Best products & <br />
          brands in our store
        </h1>
        <p>
          Trendy Products, Factory Prices, Excellent Service
        </p>
        <button type="button" class="btn btn-outline-light">
          Learn more
        </button>
        <button type="button" class="btn btn-light shadow-0 text-primary pt-2 border border-white">
          <span class="pt-1">Purchase now</span>
        </button>
      </div>
    </div>
  <section>
    <div class="container my-5">
      <header class="mb-4">
        <h3>New products</h3>
      </header>
  

      
      <div class="row">
        
        {% for stuffs in product %}
            {% if stuffs %}
            <a href="{{ url_for("product.products", product_namez=stuffs.product_name, product_id=stuffs.id) }}">
        <div class="col-lg-3 col-md-6 col-sm-6 d-flex">
          <div class="card w-100 my-2 shadow-2-strong">
            
            <img src="{{  url_for('static', filename='products/' + stuffs.product_img1 ) }}" class="card-img-top" style="aspect-ratio: 1 / 1" />
            
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"> {{ stuffs.product_name }} </h5>
              <p class="card-text">₦{{ stuffs.price }}.00</p>
              <div class="card-footer d-flex align-items-end pt-3 px-0 pb-0 mt-auto">
                <a href="{{  url_for('product.add_to_carts', id=stuffs.id ) }}" class="btn btn-primary shadow-0 me-1">Add to cart</a>
                <a href="{{  url_for('product.add_to_wishlists', id=stuffs.id ) }}" class="btn btn-light border px-2 pt-2 icon-hover">wishlist</i></a>
              </div>
            </div>
          </div>
        </div>
      </a>
        {% endif %}
        {% endfor %}
      </div>
  </section>
 

  {% endblock %}


  {% block footer %}
  <!-- Feature -->
<section class="mt-5" style="background-color: #f5f5f5;">
  <div class="container text-dark pt-3">
    <header class="pt-4 pb-3">
      <h3>Why choose us</h3>
    </header>

    <div class="row mb-4">
      <div class="col-lg-4 col-md-6">
        <figure class="d-flex align-items-center mb-4">
          <span class="rounded-circle bg-white p-3 d-flex me-2 mb-2">
            <i class="fas fa-camera-retro fa-2x fa-fw text-primary floating"></i>
          </span>
          <figcaption class="info">
            <h6 class="title">Reasonable prices</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
          </figcaption>
        </figure>
        <!-- itemside // -->
      </div>
      <!-- col // -->
      <div class="col-lg-4 col-md-6">
        <figure class="d-flex align-items-center mb-4">
          <span class="rounded-circle bg-white p-3 d-flex me-2 mb-2">
            <i class="fas fa-star fa-2x fa-fw text-primary floating"></i>
          </span>
          <figcaption class="info">
            <h6 class="title">Best quality</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
          </figcaption>
        </figure>
        <!-- itemside // -->
      </div>
      <!-- col // -->
      <div class="col-lg-4 col-md-6">
        <figure class="d-flex align-items-center mb-4">
          <span class="rounded-circle bg-white p-3 d-flex me-2 mb-2">
            <i class="fas fa-plane fa-2x fa-fw text-primary floating"></i>
          </span>
          <figcaption class="info">
            <h6 class="title">Worldwide shipping</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
          </figcaption>
        </figure>
        <!-- itemside // -->
      </div>
      <!-- col // -->
      <div class="col-lg-4 col-md-6">
        <figure class="d-flex align-items-center mb-4">
          <span class="rounded-circle bg-white p-3 d-flex me-2 mb-2">
            <i class="fas fa-users fa-2x fa-fw text-primary floating"></i>
          </span>
          <figcaption class="info">
            <h6 class="title">Customer satisfaction</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
          </figcaption>
        </figure>
        <!-- itemside // -->
      </div>
      <!-- col // -->
      <div class="col-lg-4 col-md-6">
        <figure class="d-flex align-items-center mb-4">
          <span class="rounded-circle bg-white p-3 d-flex me-2 mb-2">
            <i class="fas fa-thumbs-up fa-2x fa-fw text-primary floating"></i>
          </span>
          <figcaption class="info">
            <h6 class="title">Happy customers</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
          </figcaption>
        </figure>
        <!-- itemside // -->
      </div>
      <!-- col // -->
      <div class="col-lg-4 col-md-6">
        <figure class="d-flex align-items-center mb-4">
          <span class="rounded-circle bg-white p-3 d-flex me-2 mb-2">
            <i class="fas fa-box fa-2x fa-fw text-primary floating"></i>
          </span>
          <figcaption class="info">
            <h6 class="title">Thousand items</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
          </figcaption>
        </figure>
        <!-- itemside // -->
      </div>
      <!-- col // -->
    </div>
  </div>
  <!-- container end.// -->
</section>
<!-- Feature -->


<!-- Footer -->
<footer class="text-center text-lg-start text-muted mt-3" style="background-color: #f5f5f5;">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start pt-4 pb-4">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-12 col-lg-3 col-sm-12 mb-2">
          <!-- Content -->
          <a href="https://mdbootstrap.com/" target="_blank" class="">
            <img src="https://web.facebook.com/photo/?fbid=744957560976268&set=a.639915788147113" height="35" />
          </a>
          <p class="mt-2 text-dark">
            ...
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-6 col-sm-4 col-lg-2">
          <!-- Links -->
          <h6 class="text-uppercase text-dark fw-bold mb-2">
            Store
          </h6>
          <ul class="list-unstyled mb-4">
            <li><a class="text-muted" href="#">About us</a></li>
            <li><a class="text-muted" href="#">Find store</a></li>
            <li><a class="text-muted" href="#">Categories</a></li>
            <li><a class="text-muted" href="#">Blogs</a></li>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-6 col-sm-4 col-lg-2">
          <!-- Links -->
          <h6 class="text-uppercase text-dark fw-bold mb-2">
            Information
          </h6>
          <ul class="list-unstyled mb-4">
            <li><a class="text-muted" href="#">Help center</a></li>
            <li><a class="text-muted" href="#">Money refund</a></li>
            <li><a class="text-muted" href="#">Shipping info</a></li>
            <li><a class="text-muted" href="#">Refunds</a></li>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-6 col-sm-4 col-lg-2">
          <!-- Links -->
          <h6 class="text-uppercase text-dark fw-bold mb-2">
            Support
          </h6>
          <ul class="list-unstyled mb-4">
            <li><a class="text-muted" href="#">Help center</a></li>
            <li><a class="text-muted" href="#">Documents</a></li>
            <li><a class="text-muted" href="#">Account restore</a></li>
            <li><a class="text-muted" href="#">My orders</a></li>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-12 col-sm-12 col-lg-3">
          <!-- Links -->
          <h6 class="text-uppercase text-dark fw-bold mb-2">Newsletter</h6>
          <p class="text-muted">Stay in touch with latest updates about our products and offers</p>
          <div class="input-group mb-3">
            <input type="email" class="form-control border" placeholder="Email" aria-label="Email" aria-describedby="button-addon2" />
            <button class="btn btn-light border shadow-0" type="button" id="button-addon2" data-mdb-ripple-color="dark">
              Join
            </button>
          </div>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <div class="">
    <div class="container">
      <div class="d-flex justify-content-between py-4 border-top">
        <!--- payment --->
        <div>
          <i class="fab fa-lg fa-cc-visa text-dark"></i>
          <i class="fab fa-lg fa-cc-amex text-dark"></i>
          <i class="fab fa-lg fa-cc-mastercard text-dark"></i>
          <i class="fab fa-lg fa-cc-paypal text-dark"></i>
        </div>
        <!--- payment --->

        <!--- language selector --->
        <div class="dropdown dropup">
          <a class="dropdown-toggle text-dark" href="#" id="Dropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false"> <i class="flag-united-kingdom flag m-0 me-1"></i>English </a>

          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="Dropdown">
            <li>
              <a class="dropdown-item" href="#"><i class="flag-united-kingdom flag"></i>English <i class="fa fa-check text-success ms-2"></i></a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-poland flag"></i>Polski</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-china flag"></i>中文</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-japan flag"></i>日本語</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-germany flag"></i>Deutsch</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-france flag"></i>Français</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-spain flag"></i>Español</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-russia flag"></i>Русский</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-portugal flag"></i>Português</a>
            </li>
          </ul>
        </div>
        <!--- language selector --->
      </div>
    </div>
  </div>
</footer>
<!-- Footer -->
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="content-section">
    
    <form method='POST', action="">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
        
            <div data-mdb-input-init class="form-outline mb-4">
                {{ form.email.label(class = 'form-control-label') }}
                {% if form.email.errors %}
                            {{ form.email (class="form-control is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.email.errors %}
                                      <span>{{error}}</span>
                                  {% endfor %}
                          {% else %}
                              {{ form.email (class = 'form-control') }}
                          {% endif %}
              </div>
            
              <!-- Password input -->
              <div data-mdb-input-init class="form-outline mb-4">
                {{ form.password.label(class = 'form-control-label') }}
          
          
                          {% if form.password.errors %}
                          {{ form.password(class = 'form-control form-control-lg is-invalid') }}
                              <div class="invalid-feedback">
                                  {% for error in form.password.errors %}
                                      <span>{{error}}</span>
                                  {% endfor %}
                          {% else %}
                          {{ form.password(class = 'form-control ') }}
                          {% endif %}
              </div>
          

               <!-- Submit button -->
    {{form.submit  (class="btn btn-primary" ) }}
    
{% endblock content %}